development:
  app: 'tz'
  secret_key_base: 1c32a356878cd60541e1c7d429aead6665d3c3af316d724764aeae9c1bbe54e70911a6154e898cd9f37479aca10f55bfcf46c02b1b49b0da9cc70f20052fa084
  carrierwave:
    storage: 'file'
  # smtp_server: smtp.gmail.com
  # smtp_port: 587
  # smtp_user_name: tueusut@gmail.com
  # smtp_password: testUtest

test:
  app: 'TEST'
  access_token: 'access@token@test'
  secret_key_base: 33607cdd984ccfdb6308ada5a07c7e3ae89fea1fdeb1f41e77ff9d93cb598f1a1136cf625d84c5da43672ea95ab3844fbe0a611f0fd185fac18d1e57159684c4
  carrierwave:
    storage: 'file'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  app: <%= ENV["APP"] %>
  domain: <%= ENV["DOMAIN"] %>
  access_token: <%= ENV["ACCESS_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_server: <%= ENV["SMTP_SERVER"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  carrierwave:
    storage: <%= ENV["CARRIERWAVE_STORAGE"] %>
    fog_directory: <%= ENV["FOG_DIRECTORY"] %>
